# примеры API-запросов

@baseUrl = http://127.0.0.1:8000/api

# получение объявлений (доступно без токена)
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления (требуется токен)
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 34f373ccc469446a103f9c611707f80b00bff78b

{
  "title": "Объявление №1",
  "description": "Тестовое объявление"
}

###

# попытка поменять объявление (требуется токен и авторство)
PATCH {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token 34f373ccc469446a103f9c611707f80b00bff78b

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json

###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=OPEN
Content-Type: application/json